/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinition
        //private DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinition instance;

        public DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinition
            //instance = new DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinition> (instance, "variable 'instance' is a DestinyDefinitionsProgressionDestinyProgressionLevelRequirementDefinition");
        }


        /// <summary>
        /// Test the property 'RequirementCurve'
        /// </summary>
        [Fact]
        public void RequirementCurveTest()
        {
            // TODO unit test for the property 'RequirementCurve'
        }
        /// <summary>
        /// Test the property 'ProgressionHash'
        /// </summary>
        [Fact]
        public void ProgressionHashTest()
        {
            // TODO unit test for the property 'ProgressionHash'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Fact]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }

    }

}
