/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition
        //private DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition instance;

        public DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition
            //instance = new DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition> (instance, "variable 'instance' is a DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition");
        }


        /// <summary>
        /// Test the property 'CategoryHash'
        /// </summary>
        [Fact]
        public void CategoryHashTest()
        {
            // TODO unit test for the property 'CategoryHash'
        }
        /// <summary>
        /// Test the property 'CategoryIdentifier'
        /// </summary>
        [Fact]
        public void CategoryIdentifierTest()
        {
            // TODO unit test for the property 'CategoryIdentifier'
        }
        /// <summary>
        /// Test the property 'ReinitializationPossiblePlugHashes'
        /// </summary>
        [Fact]
        public void ReinitializationPossiblePlugHashesTest()
        {
            // TODO unit test for the property 'ReinitializationPossiblePlugHashes'
        }

    }

}
