/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyResponsesDestinyProfileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyResponsesDestinyProfileResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyResponsesDestinyProfileResponse
        //private DestinyResponsesDestinyProfileResponse instance;

        public DestinyResponsesDestinyProfileResponseTests()
        {
            // TODO uncomment below to create an instance of DestinyResponsesDestinyProfileResponse
            //instance = new DestinyResponsesDestinyProfileResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyResponsesDestinyProfileResponse
        /// </summary>
        [Fact]
        public void DestinyResponsesDestinyProfileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyResponsesDestinyProfileResponse
            //Assert.IsInstanceOfType<DestinyResponsesDestinyProfileResponse> (instance, "variable 'instance' is a DestinyResponsesDestinyProfileResponse");
        }


        /// <summary>
        /// Test the property 'VendorReceipts'
        /// </summary>
        [Fact]
        public void VendorReceiptsTest()
        {
            // TODO unit test for the property 'VendorReceipts'
        }
        /// <summary>
        /// Test the property 'ProfileInventory'
        /// </summary>
        [Fact]
        public void ProfileInventoryTest()
        {
            // TODO unit test for the property 'ProfileInventory'
        }
        /// <summary>
        /// Test the property 'ProfileCurrencies'
        /// </summary>
        [Fact]
        public void ProfileCurrenciesTest()
        {
            // TODO unit test for the property 'ProfileCurrencies'
        }
        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Fact]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }
        /// <summary>
        /// Test the property 'PlatformSilver'
        /// </summary>
        [Fact]
        public void PlatformSilverTest()
        {
            // TODO unit test for the property 'PlatformSilver'
        }
        /// <summary>
        /// Test the property 'ProfileKiosks'
        /// </summary>
        [Fact]
        public void ProfileKiosksTest()
        {
            // TODO unit test for the property 'ProfileKiosks'
        }
        /// <summary>
        /// Test the property 'ProfilePlugSets'
        /// </summary>
        [Fact]
        public void ProfilePlugSetsTest()
        {
            // TODO unit test for the property 'ProfilePlugSets'
        }
        /// <summary>
        /// Test the property 'ProfileProgression'
        /// </summary>
        [Fact]
        public void ProfileProgressionTest()
        {
            // TODO unit test for the property 'ProfileProgression'
        }
        /// <summary>
        /// Test the property 'ProfilePresentationNodes'
        /// </summary>
        [Fact]
        public void ProfilePresentationNodesTest()
        {
            // TODO unit test for the property 'ProfilePresentationNodes'
        }
        /// <summary>
        /// Test the property 'ProfileRecords'
        /// </summary>
        [Fact]
        public void ProfileRecordsTest()
        {
            // TODO unit test for the property 'ProfileRecords'
        }
        /// <summary>
        /// Test the property 'ProfileCollectibles'
        /// </summary>
        [Fact]
        public void ProfileCollectiblesTest()
        {
            // TODO unit test for the property 'ProfileCollectibles'
        }
        /// <summary>
        /// Test the property 'ProfileTransitoryData'
        /// </summary>
        [Fact]
        public void ProfileTransitoryDataTest()
        {
            // TODO unit test for the property 'ProfileTransitoryData'
        }
        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Fact]
        public void MetricsTest()
        {
            // TODO unit test for the property 'Metrics'
        }
        /// <summary>
        /// Test the property 'Characters'
        /// </summary>
        [Fact]
        public void CharactersTest()
        {
            // TODO unit test for the property 'Characters'
        }
        /// <summary>
        /// Test the property 'CharacterInventories'
        /// </summary>
        [Fact]
        public void CharacterInventoriesTest()
        {
            // TODO unit test for the property 'CharacterInventories'
        }
        /// <summary>
        /// Test the property 'CharacterProgressions'
        /// </summary>
        [Fact]
        public void CharacterProgressionsTest()
        {
            // TODO unit test for the property 'CharacterProgressions'
        }
        /// <summary>
        /// Test the property 'CharacterRenderData'
        /// </summary>
        [Fact]
        public void CharacterRenderDataTest()
        {
            // TODO unit test for the property 'CharacterRenderData'
        }
        /// <summary>
        /// Test the property 'CharacterActivities'
        /// </summary>
        [Fact]
        public void CharacterActivitiesTest()
        {
            // TODO unit test for the property 'CharacterActivities'
        }
        /// <summary>
        /// Test the property 'CharacterEquipment'
        /// </summary>
        [Fact]
        public void CharacterEquipmentTest()
        {
            // TODO unit test for the property 'CharacterEquipment'
        }
        /// <summary>
        /// Test the property 'CharacterKiosks'
        /// </summary>
        [Fact]
        public void CharacterKiosksTest()
        {
            // TODO unit test for the property 'CharacterKiosks'
        }
        /// <summary>
        /// Test the property 'CharacterPlugSets'
        /// </summary>
        [Fact]
        public void CharacterPlugSetsTest()
        {
            // TODO unit test for the property 'CharacterPlugSets'
        }
        /// <summary>
        /// Test the property 'CharacterUninstancedItemComponents'
        /// </summary>
        [Fact]
        public void CharacterUninstancedItemComponentsTest()
        {
            // TODO unit test for the property 'CharacterUninstancedItemComponents'
        }
        /// <summary>
        /// Test the property 'CharacterPresentationNodes'
        /// </summary>
        [Fact]
        public void CharacterPresentationNodesTest()
        {
            // TODO unit test for the property 'CharacterPresentationNodes'
        }
        /// <summary>
        /// Test the property 'CharacterRecords'
        /// </summary>
        [Fact]
        public void CharacterRecordsTest()
        {
            // TODO unit test for the property 'CharacterRecords'
        }
        /// <summary>
        /// Test the property 'CharacterCollectibles'
        /// </summary>
        [Fact]
        public void CharacterCollectiblesTest()
        {
            // TODO unit test for the property 'CharacterCollectibles'
        }
        /// <summary>
        /// Test the property 'ItemComponents'
        /// </summary>
        [Fact]
        public void ItemComponentsTest()
        {
            // TODO unit test for the property 'ItemComponents'
        }
        /// <summary>
        /// Test the property 'CharacterCurrencyLookups'
        /// </summary>
        [Fact]
        public void CharacterCurrencyLookupsTest()
        {
            // TODO unit test for the property 'CharacterCurrencyLookups'
        }

    }

}
