/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry
        //private DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry instance;

        public DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntryTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry
            //instance = new DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry
        /// </summary>
        [Fact]
        public void DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry
            //Assert.IsInstanceOfType<DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry> (instance, "variable 'instance' is a DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry");
        }


        /// <summary>
        /// Test the property 'CollectibleHash'
        /// </summary>
        [Fact]
        public void CollectibleHashTest()
        {
            // TODO unit test for the property 'CollectibleHash'
        }

    }

}
