/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyItemSetBlockDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyItemSetBlockDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyItemSetBlockDefinition
        //private DestinyDefinitionsDestinyItemSetBlockDefinition instance;

        public DestinyDefinitionsDestinyItemSetBlockDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyItemSetBlockDefinition
            //instance = new DestinyDefinitionsDestinyItemSetBlockDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyItemSetBlockDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsDestinyItemSetBlockDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyItemSetBlockDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyItemSetBlockDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyItemSetBlockDefinition");
        }


        /// <summary>
        /// Test the property 'ItemList'
        /// </summary>
        [Fact]
        public void ItemListTest()
        {
            // TODO unit test for the property 'ItemList'
        }
        /// <summary>
        /// Test the property 'RequireOrderedSetItemAdd'
        /// </summary>
        [Fact]
        public void RequireOrderedSetItemAddTest()
        {
            // TODO unit test for the property 'RequireOrderedSetItemAdd'
        }
        /// <summary>
        /// Test the property 'SetIsFeatured'
        /// </summary>
        [Fact]
        public void SetIsFeaturedTest()
        {
            // TODO unit test for the property 'SetIsFeatured'
        }
        /// <summary>
        /// Test the property 'SetType'
        /// </summary>
        [Fact]
        public void SetTypeTest()
        {
            // TODO unit test for the property 'SetType'
        }
        /// <summary>
        /// Test the property 'QuestLineName'
        /// </summary>
        [Fact]
        public void QuestLineNameTest()
        {
            // TODO unit test for the property 'QuestLineName'
        }

    }

}
