/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyRequestsActionsDestinyCharacterActionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyRequestsActionsDestinyCharacterActionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyRequestsActionsDestinyCharacterActionRequest
        //private DestinyRequestsActionsDestinyCharacterActionRequest instance;

        public DestinyRequestsActionsDestinyCharacterActionRequestTests()
        {
            // TODO uncomment below to create an instance of DestinyRequestsActionsDestinyCharacterActionRequest
            //instance = new DestinyRequestsActionsDestinyCharacterActionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyRequestsActionsDestinyCharacterActionRequest
        /// </summary>
        [Fact]
        public void DestinyRequestsActionsDestinyCharacterActionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyRequestsActionsDestinyCharacterActionRequest
            //Assert.IsInstanceOfType<DestinyRequestsActionsDestinyCharacterActionRequest> (instance, "variable 'instance' is a DestinyRequestsActionsDestinyCharacterActionRequest");
        }


        /// <summary>
        /// Test the property 'CharacterId'
        /// </summary>
        [Fact]
        public void CharacterIdTest()
        {
            // TODO unit test for the property 'CharacterId'
        }
        /// <summary>
        /// Test the property 'MembershipType'
        /// </summary>
        [Fact]
        public void MembershipTypeTest()
        {
            // TODO unit test for the property 'MembershipType'
        }

    }

}
