/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinition
        //private DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinition instance;

        public DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinition
            //instance = new DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinition");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ObjectiveHash'
        /// </summary>
        [Fact]
        public void ObjectiveHashTest()
        {
            // TODO unit test for the property 'ObjectiveHash'
        }

    }

}
