/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyItemSourceBlockDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyItemSourceBlockDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyItemSourceBlockDefinition
        //private DestinyDefinitionsDestinyItemSourceBlockDefinition instance;

        public DestinyDefinitionsDestinyItemSourceBlockDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyItemSourceBlockDefinition
            //instance = new DestinyDefinitionsDestinyItemSourceBlockDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyItemSourceBlockDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsDestinyItemSourceBlockDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyItemSourceBlockDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyItemSourceBlockDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyItemSourceBlockDefinition");
        }


        /// <summary>
        /// Test the property 'SourceHashes'
        /// </summary>
        [Fact]
        public void SourceHashesTest()
        {
            // TODO unit test for the property 'SourceHashes'
        }
        /// <summary>
        /// Test the property 'Sources'
        /// </summary>
        [Fact]
        public void SourcesTest()
        {
            // TODO unit test for the property 'Sources'
        }
        /// <summary>
        /// Test the property 'Exclusive'
        /// </summary>
        [Fact]
        public void ExclusiveTest()
        {
            // TODO unit test for the property 'Exclusive'
        }
        /// <summary>
        /// Test the property 'VendorSources'
        /// </summary>
        [Fact]
        public void VendorSourcesTest()
        {
            // TODO unit test for the property 'VendorSources'
        }

    }

}
