/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDestinyItemQuantity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDestinyItemQuantityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDestinyItemQuantity
        //private DestinyDestinyItemQuantity instance;

        public DestinyDestinyItemQuantityTests()
        {
            // TODO uncomment below to create an instance of DestinyDestinyItemQuantity
            //instance = new DestinyDestinyItemQuantity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDestinyItemQuantity
        /// </summary>
        [Fact]
        public void DestinyDestinyItemQuantityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDestinyItemQuantity
            //Assert.IsInstanceOfType<DestinyDestinyItemQuantity> (instance, "variable 'instance' is a DestinyDestinyItemQuantity");
        }


        /// <summary>
        /// Test the property 'ItemHash'
        /// </summary>
        [Fact]
        public void ItemHashTest()
        {
            // TODO unit test for the property 'ItemHash'
        }
        /// <summary>
        /// Test the property 'ItemInstanceId'
        /// </summary>
        [Fact]
        public void ItemInstanceIdTest()
        {
            // TODO unit test for the property 'ItemInstanceId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

    }

}
