/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing ForumPollResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ForumPollResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ForumPollResponse
        //private ForumPollResponse instance;

        public ForumPollResponseTests()
        {
            // TODO uncomment below to create an instance of ForumPollResponse
            //instance = new ForumPollResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ForumPollResponse
        /// </summary>
        [Fact]
        public void ForumPollResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ForumPollResponse
            //Assert.IsInstanceOfType<ForumPollResponse> (instance, "variable 'instance' is a ForumPollResponse");
        }


        /// <summary>
        /// Test the property 'TopicId'
        /// </summary>
        [Fact]
        public void TopicIdTest()
        {
            // TODO unit test for the property 'TopicId'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'TotalVotes'
        /// </summary>
        [Fact]
        public void TotalVotesTest()
        {
            // TODO unit test for the property 'TotalVotes'
        }

    }

}
