/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing SingleComponentResponseOfDestinyMetricsComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SingleComponentResponseOfDestinyMetricsComponentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SingleComponentResponseOfDestinyMetricsComponent
        //private SingleComponentResponseOfDestinyMetricsComponent instance;

        public SingleComponentResponseOfDestinyMetricsComponentTests()
        {
            // TODO uncomment below to create an instance of SingleComponentResponseOfDestinyMetricsComponent
            //instance = new SingleComponentResponseOfDestinyMetricsComponent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SingleComponentResponseOfDestinyMetricsComponent
        /// </summary>
        [Fact]
        public void SingleComponentResponseOfDestinyMetricsComponentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SingleComponentResponseOfDestinyMetricsComponent
            //Assert.IsInstanceOfType<SingleComponentResponseOfDestinyMetricsComponent> (instance, "variable 'instance' is a SingleComponentResponseOfDestinyMetricsComponent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Privacy'
        /// </summary>
        [Fact]
        public void PrivacyTest()
        {
            // TODO unit test for the property 'Privacy'
        }
        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Fact]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }

    }

}
