/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyComponentsKiosksDestinyKiosksComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyComponentsKiosksDestinyKiosksComponentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyComponentsKiosksDestinyKiosksComponent
        //private DestinyComponentsKiosksDestinyKiosksComponent instance;

        public DestinyComponentsKiosksDestinyKiosksComponentTests()
        {
            // TODO uncomment below to create an instance of DestinyComponentsKiosksDestinyKiosksComponent
            //instance = new DestinyComponentsKiosksDestinyKiosksComponent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyComponentsKiosksDestinyKiosksComponent
        /// </summary>
        [Fact]
        public void DestinyComponentsKiosksDestinyKiosksComponentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyComponentsKiosksDestinyKiosksComponent
            //Assert.IsInstanceOfType<DestinyComponentsKiosksDestinyKiosksComponent> (instance, "variable 'instance' is a DestinyComponentsKiosksDestinyKiosksComponent");
        }


        /// <summary>
        /// Test the property 'KioskItems'
        /// </summary>
        [Fact]
        public void KioskItemsTest()
        {
            // TODO unit test for the property 'KioskItems'
        }

    }

}
