/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDestinyTalentNodeStatBlock
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDestinyTalentNodeStatBlockTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDestinyTalentNodeStatBlock
        //private DestinyDestinyTalentNodeStatBlock instance;

        public DestinyDestinyTalentNodeStatBlockTests()
        {
            // TODO uncomment below to create an instance of DestinyDestinyTalentNodeStatBlock
            //instance = new DestinyDestinyTalentNodeStatBlock();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDestinyTalentNodeStatBlock
        /// </summary>
        [Fact]
        public void DestinyDestinyTalentNodeStatBlockInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDestinyTalentNodeStatBlock
            //Assert.IsInstanceOfType<DestinyDestinyTalentNodeStatBlock> (instance, "variable 'instance' is a DestinyDestinyTalentNodeStatBlock");
        }


        /// <summary>
        /// Test the property 'CurrentStepStats'
        /// </summary>
        [Fact]
        public void CurrentStepStatsTest()
        {
            // TODO unit test for the property 'CurrentStepStats'
        }
        /// <summary>
        /// Test the property 'NextStepStats'
        /// </summary>
        [Fact]
        public void NextStepStatsTest()
        {
            // TODO unit test for the property 'NextStepStats'
        }

    }

}
