/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyEntitiesVendorsDestinyVendorSaleItemComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyEntitiesVendorsDestinyVendorSaleItemComponentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyEntitiesVendorsDestinyVendorSaleItemComponent
        //private DestinyEntitiesVendorsDestinyVendorSaleItemComponent instance;

        public DestinyEntitiesVendorsDestinyVendorSaleItemComponentTests()
        {
            // TODO uncomment below to create an instance of DestinyEntitiesVendorsDestinyVendorSaleItemComponent
            //instance = new DestinyEntitiesVendorsDestinyVendorSaleItemComponent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyEntitiesVendorsDestinyVendorSaleItemComponent
        /// </summary>
        [Fact]
        public void DestinyEntitiesVendorsDestinyVendorSaleItemComponentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyEntitiesVendorsDestinyVendorSaleItemComponent
            //Assert.IsInstanceOfType<DestinyEntitiesVendorsDestinyVendorSaleItemComponent> (instance, "variable 'instance' is a DestinyEntitiesVendorsDestinyVendorSaleItemComponent");
        }


        /// <summary>
        /// Test the property 'SaleStatus'
        /// </summary>
        [Fact]
        public void SaleStatusTest()
        {
            // TODO unit test for the property 'SaleStatus'
        }
        /// <summary>
        /// Test the property 'RequiredUnlocks'
        /// </summary>
        [Fact]
        public void RequiredUnlocksTest()
        {
            // TODO unit test for the property 'RequiredUnlocks'
        }
        /// <summary>
        /// Test the property 'UnlockStatuses'
        /// </summary>
        [Fact]
        public void UnlockStatusesTest()
        {
            // TODO unit test for the property 'UnlockStatuses'
        }
        /// <summary>
        /// Test the property 'FailureIndexes'
        /// </summary>
        [Fact]
        public void FailureIndexesTest()
        {
            // TODO unit test for the property 'FailureIndexes'
        }
        /// <summary>
        /// Test the property 'Augments'
        /// </summary>
        [Fact]
        public void AugmentsTest()
        {
            // TODO unit test for the property 'Augments'
        }
        /// <summary>
        /// Test the property 'VendorItemIndex'
        /// </summary>
        [Fact]
        public void VendorItemIndexTest()
        {
            // TODO unit test for the property 'VendorItemIndex'
        }
        /// <summary>
        /// Test the property 'ItemHash'
        /// </summary>
        [Fact]
        public void ItemHashTest()
        {
            // TODO unit test for the property 'ItemHash'
        }
        /// <summary>
        /// Test the property 'OverrideStyleItemHash'
        /// </summary>
        [Fact]
        public void OverrideStyleItemHashTest()
        {
            // TODO unit test for the property 'OverrideStyleItemHash'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Costs'
        /// </summary>
        [Fact]
        public void CostsTest()
        {
            // TODO unit test for the property 'Costs'
        }
        /// <summary>
        /// Test the property 'OverrideNextRefreshDate'
        /// </summary>
        [Fact]
        public void OverrideNextRefreshDateTest()
        {
            // TODO unit test for the property 'OverrideNextRefreshDate'
        }

    }

}
