/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyBucketScope
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyBucketScopeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyBucketScope
        //private DestinyBucketScope instance;

        public DestinyBucketScopeTests()
        {
            // TODO uncomment below to create an instance of DestinyBucketScope
            //instance = new DestinyBucketScope();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyBucketScope
        /// </summary>
        [Fact]
        public void DestinyBucketScopeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyBucketScope
            //Assert.IsInstanceOfType<DestinyBucketScope> (instance, "variable 'instance' is a DestinyBucketScope");
        }



    }

}
