/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData
        //private DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData instance;

        public DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedDataTests()
        {
            // TODO uncomment below to create an instance of DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData
            //instance = new DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData
        /// </summary>
        [Fact]
        public void DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData
            //Assert.IsInstanceOfType<DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData> (instance, "variable 'instance' is a DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData");
        }


        /// <summary>
        /// Test the property 'Weapons'
        /// </summary>
        [Fact]
        public void WeaponsTest()
        {
            // TODO unit test for the property 'Weapons'
        }
        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }

    }

}
