/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing GroupsV2GroupOptionalConversationEditRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupsV2GroupOptionalConversationEditRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GroupsV2GroupOptionalConversationEditRequest
        //private GroupsV2GroupOptionalConversationEditRequest instance;

        public GroupsV2GroupOptionalConversationEditRequestTests()
        {
            // TODO uncomment below to create an instance of GroupsV2GroupOptionalConversationEditRequest
            //instance = new GroupsV2GroupOptionalConversationEditRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupsV2GroupOptionalConversationEditRequest
        /// </summary>
        [Fact]
        public void GroupsV2GroupOptionalConversationEditRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupsV2GroupOptionalConversationEditRequest
            //Assert.IsInstanceOfType<GroupsV2GroupOptionalConversationEditRequest> (instance, "variable 'instance' is a GroupsV2GroupOptionalConversationEditRequest");
        }


        /// <summary>
        /// Test the property 'ChatEnabled'
        /// </summary>
        [Fact]
        public void ChatEnabledTest()
        {
            // TODO unit test for the property 'ChatEnabled'
        }
        /// <summary>
        /// Test the property 'ChatName'
        /// </summary>
        [Fact]
        public void ChatNameTest()
        {
            // TODO unit test for the property 'ChatName'
        }
        /// <summary>
        /// Test the property 'ChatSecurity'
        /// </summary>
        [Fact]
        public void ChatSecurityTest()
        {
            // TODO unit test for the property 'ChatSecurity'
        }

    }

}
