/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing SearchResultOfPostResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResultOfPostResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResultOfPostResponse
        //private SearchResultOfPostResponse instance;

        public SearchResultOfPostResponseTests()
        {
            // TODO uncomment below to create an instance of SearchResultOfPostResponse
            //instance = new SearchResultOfPostResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResultOfPostResponse
        /// </summary>
        [Fact]
        public void SearchResultOfPostResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SearchResultOfPostResponse
            //Assert.IsInstanceOfType<SearchResultOfPostResponse> (instance, "variable 'instance' is a SearchResultOfPostResponse");
        }


        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'TotalResults'
        /// </summary>
        [Fact]
        public void TotalResultsTest()
        {
            // TODO unit test for the property 'TotalResults'
        }
        /// <summary>
        /// Test the property 'HasMore'
        /// </summary>
        [Fact]
        public void HasMoreTest()
        {
            // TODO unit test for the property 'HasMore'
        }
        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
        /// <summary>
        /// Test the property 'ReplacementContinuationToken'
        /// </summary>
        [Fact]
        public void ReplacementContinuationTokenTest()
        {
            // TODO unit test for the property 'ReplacementContinuationToken'
        }
        /// <summary>
        /// Test the property 'UseTotalResults'
        /// </summary>
        [Fact]
        public void UseTotalResultsTest()
        {
            // TODO unit test for the property 'UseTotalResults'
        }

    }

}
