/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using BungieNetApi.Client;
using BungieNetApi.Api;
using BungieNetApi.Model;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing TrendingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TrendingApiTests
    {
        private TrendingApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TrendingApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrendingApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' TrendingApi
            //Assert.IsInstanceOf(typeof(TrendingApi), instance);
        }

        
        /// <summary>
        /// Test TrendingGetTrendingCategories
        /// </summary>
        [Test]
        public void TrendingGetTrendingCategoriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.TrendingGetTrendingCategories();
            //Assert.IsInstanceOf(typeof(InlineResponse20061), response, "response is InlineResponse20061");
        }
        
        /// <summary>
        /// Test TrendingGetTrendingCategory
        /// </summary>
        [Test]
        public void TrendingGetTrendingCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categoryId = null;
            //int pageNumber = null;
            //var response = instance.TrendingGetTrendingCategory(categoryId, pageNumber);
            //Assert.IsInstanceOf(typeof(InlineResponse20062), response, "response is InlineResponse20062");
        }
        
        /// <summary>
        /// Test TrendingGetTrendingEntryDetail
        /// </summary>
        [Test]
        public void TrendingGetTrendingEntryDetailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string identifier = null;
            //int trendingEntryType = null;
            //var response = instance.TrendingGetTrendingEntryDetail(identifier, trendingEntryType);
            //Assert.IsInstanceOf(typeof(InlineResponse20063), response, "response is InlineResponse20063");
        }
        
    }

}
