/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing ContentModelsContentTypeDescription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentModelsContentTypeDescriptionTests
    {
        // TODO uncomment below to declare an instance variable for ContentModelsContentTypeDescription
        //private ContentModelsContentTypeDescription instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContentModelsContentTypeDescription
            //instance = new ContentModelsContentTypeDescription();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContentModelsContentTypeDescription
        /// </summary>
        [Test]
        public void ContentModelsContentTypeDescriptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ContentModelsContentTypeDescription
            //Assert.IsInstanceOf(typeof(ContentModelsContentTypeDescription), instance);
        }


        /// <summary>
        /// Test the property 'CType'
        /// </summary>
        [Test]
        public void CTypeTest()
        {
            // TODO unit test for the property 'CType'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ContentDescription'
        /// </summary>
        [Test]
        public void ContentDescriptionTest()
        {
            // TODO unit test for the property 'ContentDescription'
        }
        /// <summary>
        /// Test the property 'PreviewImage'
        /// </summary>
        [Test]
        public void PreviewImageTest()
        {
            // TODO unit test for the property 'PreviewImage'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'Reminder'
        /// </summary>
        [Test]
        public void ReminderTest()
        {
            // TODO unit test for the property 'Reminder'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'TagMetadata'
        /// </summary>
        [Test]
        public void TagMetadataTest()
        {
            // TODO unit test for the property 'TagMetadata'
        }
        /// <summary>
        /// Test the property 'TagMetadataItems'
        /// </summary>
        [Test]
        public void TagMetadataItemsTest()
        {
            // TODO unit test for the property 'TagMetadataItems'
        }
        /// <summary>
        /// Test the property 'UsageExamples'
        /// </summary>
        [Test]
        public void UsageExamplesTest()
        {
            // TODO unit test for the property 'UsageExamples'
        }
        /// <summary>
        /// Test the property 'ShowInContentEditor'
        /// </summary>
        [Test]
        public void ShowInContentEditorTest()
        {
            // TODO unit test for the property 'ShowInContentEditor'
        }
        /// <summary>
        /// Test the property 'TypeOf'
        /// </summary>
        [Test]
        public void TypeOfTest()
        {
            // TODO unit test for the property 'TypeOf'
        }
        /// <summary>
        /// Test the property 'BindIdentifierToProperty'
        /// </summary>
        [Test]
        public void BindIdentifierToPropertyTest()
        {
            // TODO unit test for the property 'BindIdentifierToProperty'
        }
        /// <summary>
        /// Test the property 'BoundRegex'
        /// </summary>
        [Test]
        public void BoundRegexTest()
        {
            // TODO unit test for the property 'BoundRegex'
        }
        /// <summary>
        /// Test the property 'ForceIdentifierBinding'
        /// </summary>
        [Test]
        public void ForceIdentifierBindingTest()
        {
            // TODO unit test for the property 'ForceIdentifierBinding'
        }
        /// <summary>
        /// Test the property 'AllowComments'
        /// </summary>
        [Test]
        public void AllowCommentsTest()
        {
            // TODO unit test for the property 'AllowComments'
        }
        /// <summary>
        /// Test the property 'AutoEnglishPropertyFallback'
        /// </summary>
        [Test]
        public void AutoEnglishPropertyFallbackTest()
        {
            // TODO unit test for the property 'AutoEnglishPropertyFallback'
        }
        /// <summary>
        /// Test the property 'BulkUploadable'
        /// </summary>
        [Test]
        public void BulkUploadableTest()
        {
            // TODO unit test for the property 'BulkUploadable'
        }
        /// <summary>
        /// Test the property 'Previews'
        /// </summary>
        [Test]
        public void PreviewsTest()
        {
            // TODO unit test for the property 'Previews'
        }
        /// <summary>
        /// Test the property 'SuppressCmsPath'
        /// </summary>
        [Test]
        public void SuppressCmsPathTest()
        {
            // TODO unit test for the property 'SuppressCmsPath'
        }
        /// <summary>
        /// Test the property 'PropertySections'
        /// </summary>
        [Test]
        public void PropertySectionsTest()
        {
            // TODO unit test for the property 'PropertySections'
        }

    }

}
