/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyComponentsCollectiblesDestinyCollectiblesComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyComponentsCollectiblesDestinyCollectiblesComponentTests
    {
        // TODO uncomment below to declare an instance variable for DestinyComponentsCollectiblesDestinyCollectiblesComponent
        //private DestinyComponentsCollectiblesDestinyCollectiblesComponent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyComponentsCollectiblesDestinyCollectiblesComponent
            //instance = new DestinyComponentsCollectiblesDestinyCollectiblesComponent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyComponentsCollectiblesDestinyCollectiblesComponent
        /// </summary>
        [Test]
        public void DestinyComponentsCollectiblesDestinyCollectiblesComponentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyComponentsCollectiblesDestinyCollectiblesComponent
            //Assert.IsInstanceOf(typeof(DestinyComponentsCollectiblesDestinyCollectiblesComponent), instance);
        }


        /// <summary>
        /// Test the property 'Collectibles'
        /// </summary>
        [Test]
        public void CollectiblesTest()
        {
            // TODO unit test for the property 'Collectibles'
        }
        /// <summary>
        /// Test the property 'CollectionCategoriesRootNodeHash'
        /// </summary>
        [Test]
        public void CollectionCategoriesRootNodeHashTest()
        {
            // TODO unit test for the property 'CollectionCategoriesRootNodeHash'
        }
        /// <summary>
        /// Test the property 'CollectionBadgesRootNodeHash'
        /// </summary>
        [Test]
        public void CollectionBadgesRootNodeHashTest()
        {
            // TODO unit test for the property 'CollectionBadgesRootNodeHash'
        }

    }

}
