/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyActivityModeDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyActivityModeDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyActivityModeDefinition
        //private DestinyDefinitionsDestinyActivityModeDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyActivityModeDefinition
            //instance = new DestinyDefinitionsDestinyActivityModeDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyActivityModeDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyActivityModeDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsDestinyActivityModeDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsDestinyActivityModeDefinition), instance);
        }


        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Test]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }
        /// <summary>
        /// Test the property 'PgcrImage'
        /// </summary>
        [Test]
        public void PgcrImageTest()
        {
            // TODO unit test for the property 'PgcrImage'
        }
        /// <summary>
        /// Test the property 'ModeType'
        /// </summary>
        [Test]
        public void ModeTypeTest()
        {
            // TODO unit test for the property 'ModeType'
        }
        /// <summary>
        /// Test the property 'ActivityModeCategory'
        /// </summary>
        [Test]
        public void ActivityModeCategoryTest()
        {
            // TODO unit test for the property 'ActivityModeCategory'
        }
        /// <summary>
        /// Test the property 'IsTeamBased'
        /// </summary>
        [Test]
        public void IsTeamBasedTest()
        {
            // TODO unit test for the property 'IsTeamBased'
        }
        /// <summary>
        /// Test the property 'IsAggregateMode'
        /// </summary>
        [Test]
        public void IsAggregateModeTest()
        {
            // TODO unit test for the property 'IsAggregateMode'
        }
        /// <summary>
        /// Test the property 'ParentHashes'
        /// </summary>
        [Test]
        public void ParentHashesTest()
        {
            // TODO unit test for the property 'ParentHashes'
        }
        /// <summary>
        /// Test the property 'FriendlyName'
        /// </summary>
        [Test]
        public void FriendlyNameTest()
        {
            // TODO unit test for the property 'FriendlyName'
        }
        /// <summary>
        /// Test the property 'ActivityModeMappings'
        /// </summary>
        [Test]
        public void ActivityModeMappingsTest()
        {
            // TODO unit test for the property 'ActivityModeMappings'
        }
        /// <summary>
        /// Test the property 'Display'
        /// </summary>
        [Test]
        public void DisplayTest()
        {
            // TODO unit test for the property 'Display'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Test]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }

    }

}
