/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyComponentsProfilesDestinyProfileTransitoryJoinability
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyComponentsProfilesDestinyProfileTransitoryJoinabilityTests
    {
        // TODO uncomment below to declare an instance variable for DestinyComponentsProfilesDestinyProfileTransitoryJoinability
        //private DestinyComponentsProfilesDestinyProfileTransitoryJoinability instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyComponentsProfilesDestinyProfileTransitoryJoinability
            //instance = new DestinyComponentsProfilesDestinyProfileTransitoryJoinability();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyComponentsProfilesDestinyProfileTransitoryJoinability
        /// </summary>
        [Test]
        public void DestinyComponentsProfilesDestinyProfileTransitoryJoinabilityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyComponentsProfilesDestinyProfileTransitoryJoinability
            //Assert.IsInstanceOf(typeof(DestinyComponentsProfilesDestinyProfileTransitoryJoinability), instance);
        }


        /// <summary>
        /// Test the property 'OpenSlots'
        /// </summary>
        [Test]
        public void OpenSlotsTest()
        {
            // TODO unit test for the property 'OpenSlots'
        }
        /// <summary>
        /// Test the property 'PrivacySetting'
        /// </summary>
        [Test]
        public void PrivacySettingTest()
        {
            // TODO unit test for the property 'PrivacySetting'
        }
        /// <summary>
        /// Test the property 'ClosedReasons'
        /// </summary>
        [Test]
        public void ClosedReasonsTest()
        {
            // TODO unit test for the property 'ClosedReasons'
        }

    }

}
