/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyVendorInventoryFlyoutDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyVendorInventoryFlyoutDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyVendorInventoryFlyoutDefinition
        //private DestinyDefinitionsDestinyVendorInventoryFlyoutDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyVendorInventoryFlyoutDefinition
            //instance = new DestinyDefinitionsDestinyVendorInventoryFlyoutDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyVendorInventoryFlyoutDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyVendorInventoryFlyoutDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsDestinyVendorInventoryFlyoutDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsDestinyVendorInventoryFlyoutDefinition), instance);
        }


        /// <summary>
        /// Test the property 'LockedDescription'
        /// </summary>
        [Test]
        public void LockedDescriptionTest()
        {
            // TODO unit test for the property 'LockedDescription'
        }
        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Test]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }
        /// <summary>
        /// Test the property 'Buckets'
        /// </summary>
        [Test]
        public void BucketsTest()
        {
            // TODO unit test for the property 'Buckets'
        }
        /// <summary>
        /// Test the property 'FlyoutId'
        /// </summary>
        [Test]
        public void FlyoutIdTest()
        {
            // TODO unit test for the property 'FlyoutId'
        }
        /// <summary>
        /// Test the property 'SuppressNewness'
        /// </summary>
        [Test]
        public void SuppressNewnessTest()
        {
            // TODO unit test for the property 'SuppressNewness'
        }
        /// <summary>
        /// Test the property 'EquipmentSlotHash'
        /// </summary>
        [Test]
        public void EquipmentSlotHashTest()
        {
            // TODO unit test for the property 'EquipmentSlotHash'
        }

    }

}
