/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDestinyUnlockStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDestinyUnlockStatusTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDestinyUnlockStatus
        //private DestinyDestinyUnlockStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDestinyUnlockStatus
            //instance = new DestinyDestinyUnlockStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDestinyUnlockStatus
        /// </summary>
        [Test]
        public void DestinyDestinyUnlockStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDestinyUnlockStatus
            //Assert.IsInstanceOf(typeof(DestinyDestinyUnlockStatus), instance);
        }


        /// <summary>
        /// Test the property 'UnlockHash'
        /// </summary>
        [Test]
        public void UnlockHashTest()
        {
            // TODO unit test for the property 'UnlockHash'
        }
        /// <summary>
        /// Test the property 'IsSet'
        /// </summary>
        [Test]
        public void IsSetTest()
        {
            // TODO unit test for the property 'IsSet'
        }

    }

}
