/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsCommonDestinyDisplayPropertiesDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition
        //private DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition
            //instance = new DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsCommonDestinyDisplayPropertiesDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition), instance);
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Test]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }
        /// <summary>
        /// Test the property 'IconSequences'
        /// </summary>
        [Test]
        public void IconSequencesTest()
        {
            // TODO unit test for the property 'IconSequences'
        }
        /// <summary>
        /// Test the property 'HighResIcon'
        /// </summary>
        [Test]
        public void HighResIconTest()
        {
            // TODO unit test for the property 'HighResIcon'
        }
        /// <summary>
        /// Test the property 'HasIcon'
        /// </summary>
        [Test]
        public void HasIconTest()
        {
            // TODO unit test for the property 'HasIcon'
        }

    }

}
