/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyComponentsKiosksDestinyKioskItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyComponentsKiosksDestinyKioskItemTests
    {
        // TODO uncomment below to declare an instance variable for DestinyComponentsKiosksDestinyKioskItem
        //private DestinyComponentsKiosksDestinyKioskItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyComponentsKiosksDestinyKioskItem
            //instance = new DestinyComponentsKiosksDestinyKioskItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyComponentsKiosksDestinyKioskItem
        /// </summary>
        [Test]
        public void DestinyComponentsKiosksDestinyKioskItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyComponentsKiosksDestinyKioskItem
            //Assert.IsInstanceOf(typeof(DestinyComponentsKiosksDestinyKioskItem), instance);
        }


        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'CanAcquire'
        /// </summary>
        [Test]
        public void CanAcquireTest()
        {
            // TODO unit test for the property 'CanAcquire'
        }
        /// <summary>
        /// Test the property 'FailureIndexes'
        /// </summary>
        [Test]
        public void FailureIndexesTest()
        {
            // TODO unit test for the property 'FailureIndexes'
        }
        /// <summary>
        /// Test the property 'FlavorObjective'
        /// </summary>
        [Test]
        public void FlavorObjectiveTest()
        {
            // TODO unit test for the property 'FlavorObjective'
        }

    }

}
