/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyItemQualityBlockDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyItemQualityBlockDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyItemQualityBlockDefinition
        //private DestinyDefinitionsDestinyItemQualityBlockDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyItemQualityBlockDefinition
            //instance = new DestinyDefinitionsDestinyItemQualityBlockDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyItemQualityBlockDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyItemQualityBlockDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsDestinyItemQualityBlockDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsDestinyItemQualityBlockDefinition), instance);
        }


        /// <summary>
        /// Test the property 'ItemLevels'
        /// </summary>
        [Test]
        public void ItemLevelsTest()
        {
            // TODO unit test for the property 'ItemLevels'
        }
        /// <summary>
        /// Test the property 'QualityLevel'
        /// </summary>
        [Test]
        public void QualityLevelTest()
        {
            // TODO unit test for the property 'QualityLevel'
        }
        /// <summary>
        /// Test the property 'InfusionCategoryName'
        /// </summary>
        [Test]
        public void InfusionCategoryNameTest()
        {
            // TODO unit test for the property 'InfusionCategoryName'
        }
        /// <summary>
        /// Test the property 'InfusionCategoryHash'
        /// </summary>
        [Test]
        public void InfusionCategoryHashTest()
        {
            // TODO unit test for the property 'InfusionCategoryHash'
        }
        /// <summary>
        /// Test the property 'InfusionCategoryHashes'
        /// </summary>
        [Test]
        public void InfusionCategoryHashesTest()
        {
            // TODO unit test for the property 'InfusionCategoryHashes'
        }
        /// <summary>
        /// Test the property 'ProgressionLevelRequirementHash'
        /// </summary>
        [Test]
        public void ProgressionLevelRequirementHashTest()
        {
            // TODO unit test for the property 'ProgressionLevelRequirementHash'
        }

    }

}
