/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDirectorDestinyLinkedGraphDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDirectorDestinyLinkedGraphDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDirectorDestinyLinkedGraphDefinition
        //private DestinyDefinitionsDirectorDestinyLinkedGraphDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDirectorDestinyLinkedGraphDefinition
            //instance = new DestinyDefinitionsDirectorDestinyLinkedGraphDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDirectorDestinyLinkedGraphDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDirectorDestinyLinkedGraphDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsDirectorDestinyLinkedGraphDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsDirectorDestinyLinkedGraphDefinition), instance);
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'UnlockExpression'
        /// </summary>
        [Test]
        public void UnlockExpressionTest()
        {
            // TODO unit test for the property 'UnlockExpression'
        }
        /// <summary>
        /// Test the property 'LinkedGraphId'
        /// </summary>
        [Test]
        public void LinkedGraphIdTest()
        {
            // TODO unit test for the property 'LinkedGraphId'
        }
        /// <summary>
        /// Test the property 'LinkedGraphs'
        /// </summary>
        [Test]
        public void LinkedGraphsTest()
        {
            // TODO unit test for the property 'LinkedGraphs'
        }
        /// <summary>
        /// Test the property 'Overview'
        /// </summary>
        [Test]
        public void OverviewTest()
        {
            // TODO unit test for the property 'Overview'
        }

    }

}
