/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyMilestonesDestinyMilestoneQuest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyMilestonesDestinyMilestoneQuestTests
    {
        // TODO uncomment below to declare an instance variable for DestinyMilestonesDestinyMilestoneQuest
        //private DestinyMilestonesDestinyMilestoneQuest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyMilestonesDestinyMilestoneQuest
            //instance = new DestinyMilestonesDestinyMilestoneQuest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyMilestonesDestinyMilestoneQuest
        /// </summary>
        [Test]
        public void DestinyMilestonesDestinyMilestoneQuestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyMilestonesDestinyMilestoneQuest
            //Assert.IsInstanceOf(typeof(DestinyMilestonesDestinyMilestoneQuest), instance);
        }


        /// <summary>
        /// Test the property 'QuestItemHash'
        /// </summary>
        [Test]
        public void QuestItemHashTest()
        {
            // TODO unit test for the property 'QuestItemHash'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Activity'
        /// </summary>
        [Test]
        public void ActivityTest()
        {
            // TODO unit test for the property 'Activity'
        }
        /// <summary>
        /// Test the property 'Challenges'
        /// </summary>
        [Test]
        public void ChallengesTest()
        {
            // TODO unit test for the property 'Challenges'
        }

    }

}
