/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyConstantsDestinyEnvironmentLocationMapping
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyConstantsDestinyEnvironmentLocationMappingTests
    {
        // TODO uncomment below to declare an instance variable for DestinyConstantsDestinyEnvironmentLocationMapping
        //private DestinyConstantsDestinyEnvironmentLocationMapping instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyConstantsDestinyEnvironmentLocationMapping
            //instance = new DestinyConstantsDestinyEnvironmentLocationMapping();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyConstantsDestinyEnvironmentLocationMapping
        /// </summary>
        [Test]
        public void DestinyConstantsDestinyEnvironmentLocationMappingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyConstantsDestinyEnvironmentLocationMapping
            //Assert.IsInstanceOf(typeof(DestinyConstantsDestinyEnvironmentLocationMapping), instance);
        }


        /// <summary>
        /// Test the property 'LocationHash'
        /// </summary>
        [Test]
        public void LocationHashTest()
        {
            // TODO unit test for the property 'LocationHash'
        }
        /// <summary>
        /// Test the property 'ActivationSource'
        /// </summary>
        [Test]
        public void ActivationSourceTest()
        {
            // TODO unit test for the property 'ActivationSource'
        }
        /// <summary>
        /// Test the property 'ItemHash'
        /// </summary>
        [Test]
        public void ItemHashTest()
        {
            // TODO unit test for the property 'ItemHash'
        }
        /// <summary>
        /// Test the property 'ObjectiveHash'
        /// </summary>
        [Test]
        public void ObjectiveHashTest()
        {
            // TODO unit test for the property 'ObjectiveHash'
        }
        /// <summary>
        /// Test the property 'ActivityHash'
        /// </summary>
        [Test]
        public void ActivityHashTest()
        {
            // TODO unit test for the property 'ActivityHash'
        }

    }

}
