/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyEntitiesCharactersDestinyCharacterComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyEntitiesCharactersDestinyCharacterComponentTests
    {
        // TODO uncomment below to declare an instance variable for DestinyEntitiesCharactersDestinyCharacterComponent
        //private DestinyEntitiesCharactersDestinyCharacterComponent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyEntitiesCharactersDestinyCharacterComponent
            //instance = new DestinyEntitiesCharactersDestinyCharacterComponent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyEntitiesCharactersDestinyCharacterComponent
        /// </summary>
        [Test]
        public void DestinyEntitiesCharactersDestinyCharacterComponentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyEntitiesCharactersDestinyCharacterComponent
            //Assert.IsInstanceOf(typeof(DestinyEntitiesCharactersDestinyCharacterComponent), instance);
        }


        /// <summary>
        /// Test the property 'MembershipId'
        /// </summary>
        [Test]
        public void MembershipIdTest()
        {
            // TODO unit test for the property 'MembershipId'
        }
        /// <summary>
        /// Test the property 'MembershipType'
        /// </summary>
        [Test]
        public void MembershipTypeTest()
        {
            // TODO unit test for the property 'MembershipType'
        }
        /// <summary>
        /// Test the property 'CharacterId'
        /// </summary>
        [Test]
        public void CharacterIdTest()
        {
            // TODO unit test for the property 'CharacterId'
        }
        /// <summary>
        /// Test the property 'DateLastPlayed'
        /// </summary>
        [Test]
        public void DateLastPlayedTest()
        {
            // TODO unit test for the property 'DateLastPlayed'
        }
        /// <summary>
        /// Test the property 'MinutesPlayedThisSession'
        /// </summary>
        [Test]
        public void MinutesPlayedThisSessionTest()
        {
            // TODO unit test for the property 'MinutesPlayedThisSession'
        }
        /// <summary>
        /// Test the property 'MinutesPlayedTotal'
        /// </summary>
        [Test]
        public void MinutesPlayedTotalTest()
        {
            // TODO unit test for the property 'MinutesPlayedTotal'
        }
        /// <summary>
        /// Test the property 'Light'
        /// </summary>
        [Test]
        public void LightTest()
        {
            // TODO unit test for the property 'Light'
        }
        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Test]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
        /// <summary>
        /// Test the property 'RaceHash'
        /// </summary>
        [Test]
        public void RaceHashTest()
        {
            // TODO unit test for the property 'RaceHash'
        }
        /// <summary>
        /// Test the property 'GenderHash'
        /// </summary>
        [Test]
        public void GenderHashTest()
        {
            // TODO unit test for the property 'GenderHash'
        }
        /// <summary>
        /// Test the property 'ClassHash'
        /// </summary>
        [Test]
        public void ClassHashTest()
        {
            // TODO unit test for the property 'ClassHash'
        }
        /// <summary>
        /// Test the property 'RaceType'
        /// </summary>
        [Test]
        public void RaceTypeTest()
        {
            // TODO unit test for the property 'RaceType'
        }
        /// <summary>
        /// Test the property 'ClassType'
        /// </summary>
        [Test]
        public void ClassTypeTest()
        {
            // TODO unit test for the property 'ClassType'
        }
        /// <summary>
        /// Test the property 'GenderType'
        /// </summary>
        [Test]
        public void GenderTypeTest()
        {
            // TODO unit test for the property 'GenderType'
        }
        /// <summary>
        /// Test the property 'EmblemPath'
        /// </summary>
        [Test]
        public void EmblemPathTest()
        {
            // TODO unit test for the property 'EmblemPath'
        }
        /// <summary>
        /// Test the property 'EmblemBackgroundPath'
        /// </summary>
        [Test]
        public void EmblemBackgroundPathTest()
        {
            // TODO unit test for the property 'EmblemBackgroundPath'
        }
        /// <summary>
        /// Test the property 'EmblemHash'
        /// </summary>
        [Test]
        public void EmblemHashTest()
        {
            // TODO unit test for the property 'EmblemHash'
        }
        /// <summary>
        /// Test the property 'EmblemColor'
        /// </summary>
        [Test]
        public void EmblemColorTest()
        {
            // TODO unit test for the property 'EmblemColor'
        }
        /// <summary>
        /// Test the property 'LevelProgression'
        /// </summary>
        [Test]
        public void LevelProgressionTest()
        {
            // TODO unit test for the property 'LevelProgression'
        }
        /// <summary>
        /// Test the property 'BaseCharacterLevel'
        /// </summary>
        [Test]
        public void BaseCharacterLevelTest()
        {
            // TODO unit test for the property 'BaseCharacterLevel'
        }
        /// <summary>
        /// Test the property 'PercentToNextLevel'
        /// </summary>
        [Test]
        public void PercentToNextLevelTest()
        {
            // TODO unit test for the property 'PercentToNextLevel'
        }
        /// <summary>
        /// Test the property 'TitleRecordHash'
        /// </summary>
        [Test]
        public void TitleRecordHashTest()
        {
            // TODO unit test for the property 'TitleRecordHash'
        }

    }

}
