/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyHistoricalStatsDestinyPostGameCarnageReportEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyHistoricalStatsDestinyPostGameCarnageReportEntryTests
    {
        // TODO uncomment below to declare an instance variable for DestinyHistoricalStatsDestinyPostGameCarnageReportEntry
        //private DestinyHistoricalStatsDestinyPostGameCarnageReportEntry instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyHistoricalStatsDestinyPostGameCarnageReportEntry
            //instance = new DestinyHistoricalStatsDestinyPostGameCarnageReportEntry();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyHistoricalStatsDestinyPostGameCarnageReportEntry
        /// </summary>
        [Test]
        public void DestinyHistoricalStatsDestinyPostGameCarnageReportEntryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyHistoricalStatsDestinyPostGameCarnageReportEntry
            //Assert.IsInstanceOf(typeof(DestinyHistoricalStatsDestinyPostGameCarnageReportEntry), instance);
        }


        /// <summary>
        /// Test the property 'Standing'
        /// </summary>
        [Test]
        public void StandingTest()
        {
            // TODO unit test for the property 'Standing'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'Player'
        /// </summary>
        [Test]
        public void PlayerTest()
        {
            // TODO unit test for the property 'Player'
        }
        /// <summary>
        /// Test the property 'CharacterId'
        /// </summary>
        [Test]
        public void CharacterIdTest()
        {
            // TODO unit test for the property 'CharacterId'
        }
        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Test]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
        /// <summary>
        /// Test the property 'Extended'
        /// </summary>
        [Test]
        public void ExtendedTest()
        {
            // TODO unit test for the property 'Extended'
        }

    }

}
