/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsRecordsDestinyRecordDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsRecordsDestinyRecordDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsRecordsDestinyRecordDefinition
        //private DestinyDefinitionsRecordsDestinyRecordDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsRecordsDestinyRecordDefinition
            //instance = new DestinyDefinitionsRecordsDestinyRecordDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsRecordsDestinyRecordDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsRecordsDestinyRecordDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsRecordsDestinyRecordDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsRecordsDestinyRecordDefinition), instance);
        }


        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Test]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }
        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Test]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }
        /// <summary>
        /// Test the property 'PresentationInfo'
        /// </summary>
        [Test]
        public void PresentationInfoTest()
        {
            // TODO unit test for the property 'PresentationInfo'
        }
        /// <summary>
        /// Test the property 'LoreHash'
        /// </summary>
        [Test]
        public void LoreHashTest()
        {
            // TODO unit test for the property 'LoreHash'
        }
        /// <summary>
        /// Test the property 'ObjectiveHashes'
        /// </summary>
        [Test]
        public void ObjectiveHashesTest()
        {
            // TODO unit test for the property 'ObjectiveHashes'
        }
        /// <summary>
        /// Test the property 'RecordValueStyle'
        /// </summary>
        [Test]
        public void RecordValueStyleTest()
        {
            // TODO unit test for the property 'RecordValueStyle'
        }
        /// <summary>
        /// Test the property 'TitleInfo'
        /// </summary>
        [Test]
        public void TitleInfoTest()
        {
            // TODO unit test for the property 'TitleInfo'
        }
        /// <summary>
        /// Test the property 'CompletionInfo'
        /// </summary>
        [Test]
        public void CompletionInfoTest()
        {
            // TODO unit test for the property 'CompletionInfo'
        }
        /// <summary>
        /// Test the property 'StateInfo'
        /// </summary>
        [Test]
        public void StateInfoTest()
        {
            // TODO unit test for the property 'StateInfo'
        }
        /// <summary>
        /// Test the property 'Requirements'
        /// </summary>
        [Test]
        public void RequirementsTest()
        {
            // TODO unit test for the property 'Requirements'
        }
        /// <summary>
        /// Test the property 'ExpirationInfo'
        /// </summary>
        [Test]
        public void ExpirationInfoTest()
        {
            // TODO unit test for the property 'ExpirationInfo'
        }
        /// <summary>
        /// Test the property 'IntervalInfo'
        /// </summary>
        [Test]
        public void IntervalInfoTest()
        {
            // TODO unit test for the property 'IntervalInfo'
        }
        /// <summary>
        /// Test the property 'RewardItems'
        /// </summary>
        [Test]
        public void RewardItemsTest()
        {
            // TODO unit test for the property 'RewardItems'
        }
        /// <summary>
        /// Test the property 'PresentationNodeType'
        /// </summary>
        [Test]
        public void PresentationNodeTypeTest()
        {
            // TODO unit test for the property 'PresentationNodeType'
        }
        /// <summary>
        /// Test the property 'TraitIds'
        /// </summary>
        [Test]
        public void TraitIdsTest()
        {
            // TODO unit test for the property 'TraitIds'
        }
        /// <summary>
        /// Test the property 'TraitHashes'
        /// </summary>
        [Test]
        public void TraitHashesTest()
        {
            // TODO unit test for the property 'TraitHashes'
        }
        /// <summary>
        /// Test the property 'ParentNodeHashes'
        /// </summary>
        [Test]
        public void ParentNodeHashesTest()
        {
            // TODO unit test for the property 'ParentNodeHashes'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Test]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }

    }

}
