/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DictionaryComponentResponseOfint64AndDestinyItemPerksComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DictionaryComponentResponseOfint64AndDestinyItemPerksComponentTests
    {
        // TODO uncomment below to declare an instance variable for DictionaryComponentResponseOfint64AndDestinyItemPerksComponent
        //private DictionaryComponentResponseOfint64AndDestinyItemPerksComponent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DictionaryComponentResponseOfint64AndDestinyItemPerksComponent
            //instance = new DictionaryComponentResponseOfint64AndDestinyItemPerksComponent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DictionaryComponentResponseOfint64AndDestinyItemPerksComponent
        /// </summary>
        [Test]
        public void DictionaryComponentResponseOfint64AndDestinyItemPerksComponentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DictionaryComponentResponseOfint64AndDestinyItemPerksComponent
            //Assert.IsInstanceOf(typeof(DictionaryComponentResponseOfint64AndDestinyItemPerksComponent), instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Privacy'
        /// </summary>
        [Test]
        public void PrivacyTest()
        {
            // TODO unit test for the property 'Privacy'
        }
        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Test]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }

    }

}
