/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing GroupsV2GroupOptionalConversation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupsV2GroupOptionalConversationTests
    {
        // TODO uncomment below to declare an instance variable for GroupsV2GroupOptionalConversation
        //private GroupsV2GroupOptionalConversation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupsV2GroupOptionalConversation
            //instance = new GroupsV2GroupOptionalConversation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupsV2GroupOptionalConversation
        /// </summary>
        [Test]
        public void GroupsV2GroupOptionalConversationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GroupsV2GroupOptionalConversation
            //Assert.IsInstanceOf(typeof(GroupsV2GroupOptionalConversation), instance);
        }


        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Test]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
        /// <summary>
        /// Test the property 'ConversationId'
        /// </summary>
        [Test]
        public void ConversationIdTest()
        {
            // TODO unit test for the property 'ConversationId'
        }
        /// <summary>
        /// Test the property 'ChatEnabled'
        /// </summary>
        [Test]
        public void ChatEnabledTest()
        {
            // TODO unit test for the property 'ChatEnabled'
        }
        /// <summary>
        /// Test the property 'ChatName'
        /// </summary>
        [Test]
        public void ChatNameTest()
        {
            // TODO unit test for the property 'ChatName'
        }
        /// <summary>
        /// Test the property 'ChatSecurity'
        /// </summary>
        [Test]
        public void ChatSecurityTest()
        {
            // TODO unit test for the property 'ChatSecurity'
        }

    }

}
