/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20056
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse20056Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20056
        //private InlineResponse20056 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20056
            //instance = new InlineResponse20056();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20056
        /// </summary>
        [Test]
        public void InlineResponse20056InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse20056
            //Assert.IsInstanceOf(typeof(InlineResponse20056), instance);
        }


        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Test]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }
        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Test]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'ThrottleSeconds'
        /// </summary>
        [Test]
        public void ThrottleSecondsTest()
        {
            // TODO unit test for the property 'ThrottleSeconds'
        }
        /// <summary>
        /// Test the property 'ErrorStatus'
        /// </summary>
        [Test]
        public void ErrorStatusTest()
        {
            // TODO unit test for the property 'ErrorStatus'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'MessageData'
        /// </summary>
        [Test]
        public void MessageDataTest()
        {
            // TODO unit test for the property 'MessageData'
        }
        /// <summary>
        /// Test the property 'DetailedErrorTrace'
        /// </summary>
        [Test]
        public void DetailedErrorTraceTest()
        {
            // TODO unit test for the property 'DetailedErrorTrace'
        }

    }

}
