/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing SearchResultOfContentItemPublicContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResultOfContentItemPublicContractTests
    {
        // TODO uncomment below to declare an instance variable for SearchResultOfContentItemPublicContract
        //private SearchResultOfContentItemPublicContract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SearchResultOfContentItemPublicContract
            //instance = new SearchResultOfContentItemPublicContract();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchResultOfContentItemPublicContract
        /// </summary>
        [Test]
        public void SearchResultOfContentItemPublicContractInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SearchResultOfContentItemPublicContract
            //Assert.IsInstanceOf(typeof(SearchResultOfContentItemPublicContract), instance);
        }


        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'TotalResults'
        /// </summary>
        [Test]
        public void TotalResultsTest()
        {
            // TODO unit test for the property 'TotalResults'
        }
        /// <summary>
        /// Test the property 'HasMore'
        /// </summary>
        [Test]
        public void HasMoreTest()
        {
            // TODO unit test for the property 'HasMore'
        }
        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Test]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
        /// <summary>
        /// Test the property 'ReplacementContinuationToken'
        /// </summary>
        [Test]
        public void ReplacementContinuationTokenTest()
        {
            // TODO unit test for the property 'ReplacementContinuationToken'
        }
        /// <summary>
        /// Test the property 'UseTotalResults'
        /// </summary>
        [Test]
        public void UseTotalResultsTest()
        {
            // TODO unit test for the property 'UseTotalResults'
        }

    }

}
