/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing UserEmailViewDefinitionSetting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserEmailViewDefinitionSettingTests
    {
        // TODO uncomment below to declare an instance variable for UserEmailViewDefinitionSetting
        //private UserEmailViewDefinitionSetting instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserEmailViewDefinitionSetting
            //instance = new UserEmailViewDefinitionSetting();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserEmailViewDefinitionSetting
        /// </summary>
        [Test]
        public void UserEmailViewDefinitionSettingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UserEmailViewDefinitionSetting
            //Assert.IsInstanceOf(typeof(UserEmailViewDefinitionSetting), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Localization'
        /// </summary>
        [Test]
        public void LocalizationTest()
        {
            // TODO unit test for the property 'Localization'
        }
        /// <summary>
        /// Test the property 'SetByDefault'
        /// </summary>
        [Test]
        public void SetByDefaultTest()
        {
            // TODO unit test for the property 'SetByDefault'
        }
        /// <summary>
        /// Test the property 'OptInAggregateValue'
        /// </summary>
        [Test]
        public void OptInAggregateValueTest()
        {
            // TODO unit test for the property 'OptInAggregateValue'
        }
        /// <summary>
        /// Test the property 'Subscriptions'
        /// </summary>
        [Test]
        public void SubscriptionsTest()
        {
            // TODO unit test for the property 'Subscriptions'
        }

    }

}
