/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinition
        //private DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinition
            //instance = new DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinition), instance);
        }


        /// <summary>
        /// Test the property 'QuestItemHash'
        /// </summary>
        [Test]
        public void QuestItemHashTest()
        {
            // TODO unit test for the property 'QuestItemHash'
        }
        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Test]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }
        /// <summary>
        /// Test the property 'OverrideImage'
        /// </summary>
        [Test]
        public void OverrideImageTest()
        {
            // TODO unit test for the property 'OverrideImage'
        }
        /// <summary>
        /// Test the property 'QuestRewards'
        /// </summary>
        [Test]
        public void QuestRewardsTest()
        {
            // TODO unit test for the property 'QuestRewards'
        }
        /// <summary>
        /// Test the property 'Activities'
        /// </summary>
        [Test]
        public void ActivitiesTest()
        {
            // TODO unit test for the property 'Activities'
        }
        /// <summary>
        /// Test the property 'DestinationHash'
        /// </summary>
        [Test]
        public void DestinationHashTest()
        {
            // TODO unit test for the property 'DestinationHash'
        }

    }

}
