/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyHistoricalStatsDestinyPlayer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyHistoricalStatsDestinyPlayerTests
    {
        // TODO uncomment below to declare an instance variable for DestinyHistoricalStatsDestinyPlayer
        //private DestinyHistoricalStatsDestinyPlayer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyHistoricalStatsDestinyPlayer
            //instance = new DestinyHistoricalStatsDestinyPlayer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyHistoricalStatsDestinyPlayer
        /// </summary>
        [Test]
        public void DestinyHistoricalStatsDestinyPlayerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyHistoricalStatsDestinyPlayer
            //Assert.IsInstanceOf(typeof(DestinyHistoricalStatsDestinyPlayer), instance);
        }


        /// <summary>
        /// Test the property 'DestinyUserInfo'
        /// </summary>
        [Test]
        public void DestinyUserInfoTest()
        {
            // TODO unit test for the property 'DestinyUserInfo'
        }
        /// <summary>
        /// Test the property 'CharacterClass'
        /// </summary>
        [Test]
        public void CharacterClassTest()
        {
            // TODO unit test for the property 'CharacterClass'
        }
        /// <summary>
        /// Test the property 'ClassHash'
        /// </summary>
        [Test]
        public void ClassHashTest()
        {
            // TODO unit test for the property 'ClassHash'
        }
        /// <summary>
        /// Test the property 'RaceHash'
        /// </summary>
        [Test]
        public void RaceHashTest()
        {
            // TODO unit test for the property 'RaceHash'
        }
        /// <summary>
        /// Test the property 'GenderHash'
        /// </summary>
        [Test]
        public void GenderHashTest()
        {
            // TODO unit test for the property 'GenderHash'
        }
        /// <summary>
        /// Test the property 'CharacterLevel'
        /// </summary>
        [Test]
        public void CharacterLevelTest()
        {
            // TODO unit test for the property 'CharacterLevel'
        }
        /// <summary>
        /// Test the property 'LightLevel'
        /// </summary>
        [Test]
        public void LightLevelTest()
        {
            // TODO unit test for the property 'LightLevel'
        }
        /// <summary>
        /// Test the property 'BungieNetUserInfo'
        /// </summary>
        [Test]
        public void BungieNetUserInfoTest()
        {
            // TODO unit test for the property 'BungieNetUserInfo'
        }
        /// <summary>
        /// Test the property 'ClanName'
        /// </summary>
        [Test]
        public void ClanNameTest()
        {
            // TODO unit test for the property 'ClanName'
        }
        /// <summary>
        /// Test the property 'ClanTag'
        /// </summary>
        [Test]
        public void ClanTagTest()
        {
            // TODO unit test for the property 'ClanTag'
        }
        /// <summary>
        /// Test the property 'EmblemHash'
        /// </summary>
        [Test]
        public void EmblemHashTest()
        {
            // TODO unit test for the property 'EmblemHash'
        }

    }

}
