/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyMilestonesDestinyMilestoneActivity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyMilestonesDestinyMilestoneActivityTests
    {
        // TODO uncomment below to declare an instance variable for DestinyMilestonesDestinyMilestoneActivity
        //private DestinyMilestonesDestinyMilestoneActivity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyMilestonesDestinyMilestoneActivity
            //instance = new DestinyMilestonesDestinyMilestoneActivity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyMilestonesDestinyMilestoneActivity
        /// </summary>
        [Test]
        public void DestinyMilestonesDestinyMilestoneActivityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyMilestonesDestinyMilestoneActivity
            //Assert.IsInstanceOf(typeof(DestinyMilestonesDestinyMilestoneActivity), instance);
        }


        /// <summary>
        /// Test the property 'ActivityHash'
        /// </summary>
        [Test]
        public void ActivityHashTest()
        {
            // TODO unit test for the property 'ActivityHash'
        }
        /// <summary>
        /// Test the property 'ActivityModeHash'
        /// </summary>
        [Test]
        public void ActivityModeHashTest()
        {
            // TODO unit test for the property 'ActivityModeHash'
        }
        /// <summary>
        /// Test the property 'ActivityModeType'
        /// </summary>
        [Test]
        public void ActivityModeTypeTest()
        {
            // TODO unit test for the property 'ActivityModeType'
        }
        /// <summary>
        /// Test the property 'ModifierHashes'
        /// </summary>
        [Test]
        public void ModifierHashesTest()
        {
            // TODO unit test for the property 'ModifierHashes'
        }
        /// <summary>
        /// Test the property 'Variants'
        /// </summary>
        [Test]
        public void VariantsTest()
        {
            // TODO unit test for the property 'Variants'
        }

    }

}
