/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyEquipmentSlotDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyEquipmentSlotDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyEquipmentSlotDefinition
        //private DestinyDefinitionsDestinyEquipmentSlotDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyEquipmentSlotDefinition
            //instance = new DestinyDefinitionsDestinyEquipmentSlotDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyEquipmentSlotDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyEquipmentSlotDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsDestinyEquipmentSlotDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsDestinyEquipmentSlotDefinition), instance);
        }


        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Test]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }
        /// <summary>
        /// Test the property 'EquipmentCategoryHash'
        /// </summary>
        [Test]
        public void EquipmentCategoryHashTest()
        {
            // TODO unit test for the property 'EquipmentCategoryHash'
        }
        /// <summary>
        /// Test the property 'BucketTypeHash'
        /// </summary>
        [Test]
        public void BucketTypeHashTest()
        {
            // TODO unit test for the property 'BucketTypeHash'
        }
        /// <summary>
        /// Test the property 'ApplyCustomArtDyes'
        /// </summary>
        [Test]
        public void ApplyCustomArtDyesTest()
        {
            // TODO unit test for the property 'ApplyCustomArtDyes'
        }
        /// <summary>
        /// Test the property 'ArtDyeChannels'
        /// </summary>
        [Test]
        public void ArtDyeChannelsTest()
        {
            // TODO unit test for the property 'ArtDyeChannels'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Test]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }

    }

}
