/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsPresentationDestinyPresentationNodeDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsPresentationDestinyPresentationNodeDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsPresentationDestinyPresentationNodeDefinition
        //private DestinyDefinitionsPresentationDestinyPresentationNodeDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsPresentationDestinyPresentationNodeDefinition
            //instance = new DestinyDefinitionsPresentationDestinyPresentationNodeDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsPresentationDestinyPresentationNodeDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsPresentationDestinyPresentationNodeDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsPresentationDestinyPresentationNodeDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsPresentationDestinyPresentationNodeDefinition), instance);
        }


        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Test]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }
        /// <summary>
        /// Test the property 'OriginalIcon'
        /// </summary>
        [Test]
        public void OriginalIconTest()
        {
            // TODO unit test for the property 'OriginalIcon'
        }
        /// <summary>
        /// Test the property 'RootViewIcon'
        /// </summary>
        [Test]
        public void RootViewIconTest()
        {
            // TODO unit test for the property 'RootViewIcon'
        }
        /// <summary>
        /// Test the property 'NodeType'
        /// </summary>
        [Test]
        public void NodeTypeTest()
        {
            // TODO unit test for the property 'NodeType'
        }
        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Test]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }
        /// <summary>
        /// Test the property 'ObjectiveHash'
        /// </summary>
        [Test]
        public void ObjectiveHashTest()
        {
            // TODO unit test for the property 'ObjectiveHash'
        }
        /// <summary>
        /// Test the property 'CompletionRecordHash'
        /// </summary>
        [Test]
        public void CompletionRecordHashTest()
        {
            // TODO unit test for the property 'CompletionRecordHash'
        }
        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Test]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }
        /// <summary>
        /// Test the property 'DisplayStyle'
        /// </summary>
        [Test]
        public void DisplayStyleTest()
        {
            // TODO unit test for the property 'DisplayStyle'
        }
        /// <summary>
        /// Test the property 'ScreenStyle'
        /// </summary>
        [Test]
        public void ScreenStyleTest()
        {
            // TODO unit test for the property 'ScreenStyle'
        }
        /// <summary>
        /// Test the property 'Requirements'
        /// </summary>
        [Test]
        public void RequirementsTest()
        {
            // TODO unit test for the property 'Requirements'
        }
        /// <summary>
        /// Test the property 'DisableChildSubscreenNavigation'
        /// </summary>
        [Test]
        public void DisableChildSubscreenNavigationTest()
        {
            // TODO unit test for the property 'DisableChildSubscreenNavigation'
        }
        /// <summary>
        /// Test the property 'PresentationNodeType'
        /// </summary>
        [Test]
        public void PresentationNodeTypeTest()
        {
            // TODO unit test for the property 'PresentationNodeType'
        }
        /// <summary>
        /// Test the property 'TraitIds'
        /// </summary>
        [Test]
        public void TraitIdsTest()
        {
            // TODO unit test for the property 'TraitIds'
        }
        /// <summary>
        /// Test the property 'TraitHashes'
        /// </summary>
        [Test]
        public void TraitHashesTest()
        {
            // TODO unit test for the property 'TraitHashes'
        }
        /// <summary>
        /// Test the property 'ParentNodeHashes'
        /// </summary>
        [Test]
        public void ParentNodeHashesTest()
        {
            // TODO unit test for the property 'ParentNodeHashes'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Test]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }

    }

}
