/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyRequestsActionsDestinyInsertPlugsActionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyRequestsActionsDestinyInsertPlugsActionRequestTests
    {
        // TODO uncomment below to declare an instance variable for DestinyRequestsActionsDestinyInsertPlugsActionRequest
        //private DestinyRequestsActionsDestinyInsertPlugsActionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyRequestsActionsDestinyInsertPlugsActionRequest
            //instance = new DestinyRequestsActionsDestinyInsertPlugsActionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyRequestsActionsDestinyInsertPlugsActionRequest
        /// </summary>
        [Test]
        public void DestinyRequestsActionsDestinyInsertPlugsActionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyRequestsActionsDestinyInsertPlugsActionRequest
            //Assert.IsInstanceOf(typeof(DestinyRequestsActionsDestinyInsertPlugsActionRequest), instance);
        }


        /// <summary>
        /// Test the property 'ActionToken'
        /// </summary>
        [Test]
        public void ActionTokenTest()
        {
            // TODO unit test for the property 'ActionToken'
        }
        /// <summary>
        /// Test the property 'ItemInstanceId'
        /// </summary>
        [Test]
        public void ItemInstanceIdTest()
        {
            // TODO unit test for the property 'ItemInstanceId'
        }
        /// <summary>
        /// Test the property 'Plug'
        /// </summary>
        [Test]
        public void PlugTest()
        {
            // TODO unit test for the property 'Plug'
        }
        /// <summary>
        /// Test the property 'CharacterId'
        /// </summary>
        [Test]
        public void CharacterIdTest()
        {
            // TODO unit test for the property 'CharacterId'
        }
        /// <summary>
        /// Test the property 'MembershipType'
        /// </summary>
        [Test]
        public void MembershipTypeTest()
        {
            // TODO unit test for the property 'MembershipType'
        }

    }

}
