/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyItemComponentSetOfuint32
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyItemComponentSetOfuint32Tests
    {
        // TODO uncomment below to declare an instance variable for DestinyItemComponentSetOfuint32
        //private DestinyItemComponentSetOfuint32 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyItemComponentSetOfuint32
            //instance = new DestinyItemComponentSetOfuint32();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyItemComponentSetOfuint32
        /// </summary>
        [Test]
        public void DestinyItemComponentSetOfuint32InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyItemComponentSetOfuint32
            //Assert.IsInstanceOf(typeof(DestinyItemComponentSetOfuint32), instance);
        }


        /// <summary>
        /// Test the property 'Instances'
        /// </summary>
        [Test]
        public void InstancesTest()
        {
            // TODO unit test for the property 'Instances'
        }
        /// <summary>
        /// Test the property 'Perks'
        /// </summary>
        [Test]
        public void PerksTest()
        {
            // TODO unit test for the property 'Perks'
        }
        /// <summary>
        /// Test the property 'RenderData'
        /// </summary>
        [Test]
        public void RenderDataTest()
        {
            // TODO unit test for the property 'RenderData'
        }
        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Test]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
        /// <summary>
        /// Test the property 'Sockets'
        /// </summary>
        [Test]
        public void SocketsTest()
        {
            // TODO unit test for the property 'Sockets'
        }
        /// <summary>
        /// Test the property 'ReusablePlugs'
        /// </summary>
        [Test]
        public void ReusablePlugsTest()
        {
            // TODO unit test for the property 'ReusablePlugs'
        }
        /// <summary>
        /// Test the property 'PlugObjectives'
        /// </summary>
        [Test]
        public void PlugObjectivesTest()
        {
            // TODO unit test for the property 'PlugObjectives'
        }
        /// <summary>
        /// Test the property 'TalentGrids'
        /// </summary>
        [Test]
        public void TalentGridsTest()
        {
            // TODO unit test for the property 'TalentGrids'
        }
        /// <summary>
        /// Test the property 'PlugStates'
        /// </summary>
        [Test]
        public void PlugStatesTest()
        {
            // TODO unit test for the property 'PlugStates'
        }
        /// <summary>
        /// Test the property 'Objectives'
        /// </summary>
        [Test]
        public void ObjectivesTest()
        {
            // TODO unit test for the property 'Objectives'
        }

    }

}
