/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyVendorCategoryEntryDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyVendorCategoryEntryDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyVendorCategoryEntryDefinition
        //private DestinyDefinitionsDestinyVendorCategoryEntryDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyVendorCategoryEntryDefinition
            //instance = new DestinyDefinitionsDestinyVendorCategoryEntryDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyVendorCategoryEntryDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyVendorCategoryEntryDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsDestinyVendorCategoryEntryDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsDestinyVendorCategoryEntryDefinition), instance);
        }


        /// <summary>
        /// Test the property 'CategoryIndex'
        /// </summary>
        [Test]
        public void CategoryIndexTest()
        {
            // TODO unit test for the property 'CategoryIndex'
        }
        /// <summary>
        /// Test the property 'SortValue'
        /// </summary>
        [Test]
        public void SortValueTest()
        {
            // TODO unit test for the property 'SortValue'
        }
        /// <summary>
        /// Test the property 'CategoryHash'
        /// </summary>
        [Test]
        public void CategoryHashTest()
        {
            // TODO unit test for the property 'CategoryHash'
        }
        /// <summary>
        /// Test the property 'QuantityAvailable'
        /// </summary>
        [Test]
        public void QuantityAvailableTest()
        {
            // TODO unit test for the property 'QuantityAvailable'
        }
        /// <summary>
        /// Test the property 'ShowUnavailableItems'
        /// </summary>
        [Test]
        public void ShowUnavailableItemsTest()
        {
            // TODO unit test for the property 'ShowUnavailableItems'
        }
        /// <summary>
        /// Test the property 'HideIfNoCurrency'
        /// </summary>
        [Test]
        public void HideIfNoCurrencyTest()
        {
            // TODO unit test for the property 'HideIfNoCurrency'
        }
        /// <summary>
        /// Test the property 'HideFromRegularPurchase'
        /// </summary>
        [Test]
        public void HideFromRegularPurchaseTest()
        {
            // TODO unit test for the property 'HideFromRegularPurchase'
        }
        /// <summary>
        /// Test the property 'BuyStringOverride'
        /// </summary>
        [Test]
        public void BuyStringOverrideTest()
        {
            // TODO unit test for the property 'BuyStringOverride'
        }
        /// <summary>
        /// Test the property 'DisabledDescription'
        /// </summary>
        [Test]
        public void DisabledDescriptionTest()
        {
            // TODO unit test for the property 'DisabledDescription'
        }
        /// <summary>
        /// Test the property 'DisplayTitle'
        /// </summary>
        [Test]
        public void DisplayTitleTest()
        {
            // TODO unit test for the property 'DisplayTitle'
        }
        /// <summary>
        /// Test the property 'Overlay'
        /// </summary>
        [Test]
        public void OverlayTest()
        {
            // TODO unit test for the property 'Overlay'
        }
        /// <summary>
        /// Test the property 'VendorItemIndexes'
        /// </summary>
        [Test]
        public void VendorItemIndexesTest()
        {
            // TODO unit test for the property 'VendorItemIndexes'
        }
        /// <summary>
        /// Test the property 'IsPreview'
        /// </summary>
        [Test]
        public void IsPreviewTest()
        {
            // TODO unit test for the property 'IsPreview'
        }
        /// <summary>
        /// Test the property 'IsDisplayOnly'
        /// </summary>
        [Test]
        public void IsDisplayOnlyTest()
        {
            // TODO unit test for the property 'IsDisplayOnly'
        }
        /// <summary>
        /// Test the property 'ResetIntervalMinutesOverride'
        /// </summary>
        [Test]
        public void ResetIntervalMinutesOverrideTest()
        {
            // TODO unit test for the property 'ResetIntervalMinutesOverride'
        }
        /// <summary>
        /// Test the property 'ResetOffsetMinutesOverride'
        /// </summary>
        [Test]
        public void ResetOffsetMinutesOverrideTest()
        {
            // TODO unit test for the property 'ResetOffsetMinutesOverride'
        }

    }

}
