/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyComponentsProfilesDestinyProfileTransitoryPartyMember
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyComponentsProfilesDestinyProfileTransitoryPartyMemberTests
    {
        // TODO uncomment below to declare an instance variable for DestinyComponentsProfilesDestinyProfileTransitoryPartyMember
        //private DestinyComponentsProfilesDestinyProfileTransitoryPartyMember instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyComponentsProfilesDestinyProfileTransitoryPartyMember
            //instance = new DestinyComponentsProfilesDestinyProfileTransitoryPartyMember();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyComponentsProfilesDestinyProfileTransitoryPartyMember
        /// </summary>
        [Test]
        public void DestinyComponentsProfilesDestinyProfileTransitoryPartyMemberInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyComponentsProfilesDestinyProfileTransitoryPartyMember
            //Assert.IsInstanceOf(typeof(DestinyComponentsProfilesDestinyProfileTransitoryPartyMember), instance);
        }


        /// <summary>
        /// Test the property 'MembershipId'
        /// </summary>
        [Test]
        public void MembershipIdTest()
        {
            // TODO unit test for the property 'MembershipId'
        }
        /// <summary>
        /// Test the property 'EmblemHash'
        /// </summary>
        [Test]
        public void EmblemHashTest()
        {
            // TODO unit test for the property 'EmblemHash'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
