/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyComponentsPresentationDestinyPresentationNodeComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyComponentsPresentationDestinyPresentationNodeComponentTests
    {
        // TODO uncomment below to declare an instance variable for DestinyComponentsPresentationDestinyPresentationNodeComponent
        //private DestinyComponentsPresentationDestinyPresentationNodeComponent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyComponentsPresentationDestinyPresentationNodeComponent
            //instance = new DestinyComponentsPresentationDestinyPresentationNodeComponent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyComponentsPresentationDestinyPresentationNodeComponent
        /// </summary>
        [Test]
        public void DestinyComponentsPresentationDestinyPresentationNodeComponentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyComponentsPresentationDestinyPresentationNodeComponent
            //Assert.IsInstanceOf(typeof(DestinyComponentsPresentationDestinyPresentationNodeComponent), instance);
        }


        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Objective'
        /// </summary>
        [Test]
        public void ObjectiveTest()
        {
            // TODO unit test for the property 'Objective'
        }
        /// <summary>
        /// Test the property 'ProgressValue'
        /// </summary>
        [Test]
        public void ProgressValueTest()
        {
            // TODO unit test for the property 'ProgressValue'
        }
        /// <summary>
        /// Test the property 'CompletionValue'
        /// </summary>
        [Test]
        public void CompletionValueTest()
        {
            // TODO unit test for the property 'CompletionValue'
        }

    }

}
