/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyArtifactsDestinyArtifactTier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyArtifactsDestinyArtifactTierTests
    {
        // TODO uncomment below to declare an instance variable for DestinyArtifactsDestinyArtifactTier
        //private DestinyArtifactsDestinyArtifactTier instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyArtifactsDestinyArtifactTier
            //instance = new DestinyArtifactsDestinyArtifactTier();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyArtifactsDestinyArtifactTier
        /// </summary>
        [Test]
        public void DestinyArtifactsDestinyArtifactTierInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyArtifactsDestinyArtifactTier
            //Assert.IsInstanceOf(typeof(DestinyArtifactsDestinyArtifactTier), instance);
        }


        /// <summary>
        /// Test the property 'TierHash'
        /// </summary>
        [Test]
        public void TierHashTest()
        {
            // TODO unit test for the property 'TierHash'
        }
        /// <summary>
        /// Test the property 'IsUnlocked'
        /// </summary>
        [Test]
        public void IsUnlockedTest()
        {
            // TODO unit test for the property 'IsUnlocked'
        }
        /// <summary>
        /// Test the property 'PointsToUnlock'
        /// </summary>
        [Test]
        public void PointsToUnlockTest()
        {
            // TODO unit test for the property 'PointsToUnlock'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
