/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinition
        //private DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinition
            //instance = new DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinition), instance);
        }


        /// <summary>
        /// Test the property 'NodeId'
        /// </summary>
        [Test]
        public void NodeIdTest()
        {
            // TODO unit test for the property 'NodeId'
        }
        /// <summary>
        /// Test the property 'OverrideDisplay'
        /// </summary>
        [Test]
        public void OverrideDisplayTest()
        {
            // TODO unit test for the property 'OverrideDisplay'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'FeaturingStates'
        /// </summary>
        [Test]
        public void FeaturingStatesTest()
        {
            // TODO unit test for the property 'FeaturingStates'
        }
        /// <summary>
        /// Test the property 'Activities'
        /// </summary>
        [Test]
        public void ActivitiesTest()
        {
            // TODO unit test for the property 'Activities'
        }
        /// <summary>
        /// Test the property 'States'
        /// </summary>
        [Test]
        public void StatesTest()
        {
            // TODO unit test for the property 'States'
        }

    }

}
