/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyVendorCategoryOverlayDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyVendorCategoryOverlayDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyVendorCategoryOverlayDefinition
        //private DestinyDefinitionsDestinyVendorCategoryOverlayDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyVendorCategoryOverlayDefinition
            //instance = new DestinyDefinitionsDestinyVendorCategoryOverlayDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyVendorCategoryOverlayDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyVendorCategoryOverlayDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyDefinitionsDestinyVendorCategoryOverlayDefinition
            //Assert.IsInstanceOf(typeof(DestinyDefinitionsDestinyVendorCategoryOverlayDefinition), instance);
        }


        /// <summary>
        /// Test the property 'ChoiceDescription'
        /// </summary>
        [Test]
        public void ChoiceDescriptionTest()
        {
            // TODO unit test for the property 'ChoiceDescription'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Test]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'CurrencyItemHash'
        /// </summary>
        [Test]
        public void CurrencyItemHashTest()
        {
            // TODO unit test for the property 'CurrencyItemHash'
        }

    }

}
