/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyAdvancedAwaUserResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyAdvancedAwaUserResponseTests
    {
        // TODO uncomment below to declare an instance variable for DestinyAdvancedAwaUserResponse
        //private DestinyAdvancedAwaUserResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyAdvancedAwaUserResponse
            //instance = new DestinyAdvancedAwaUserResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyAdvancedAwaUserResponse
        /// </summary>
        [Test]
        public void DestinyAdvancedAwaUserResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyAdvancedAwaUserResponse
            //Assert.IsInstanceOf(typeof(DestinyAdvancedAwaUserResponse), instance);
        }


        /// <summary>
        /// Test the property 'Selection'
        /// </summary>
        [Test]
        public void SelectionTest()
        {
            // TODO unit test for the property 'Selection'
        }
        /// <summary>
        /// Test the property 'CorrelationId'
        /// </summary>
        [Test]
        public void CorrelationIdTest()
        {
            // TODO unit test for the property 'CorrelationId'
        }
        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Test]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }

    }

}
