/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyComponentsVendorsDestinyVendorSaleItemBaseComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyComponentsVendorsDestinyVendorSaleItemBaseComponentTests
    {
        // TODO uncomment below to declare an instance variable for DestinyComponentsVendorsDestinyVendorSaleItemBaseComponent
        //private DestinyComponentsVendorsDestinyVendorSaleItemBaseComponent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyComponentsVendorsDestinyVendorSaleItemBaseComponent
            //instance = new DestinyComponentsVendorsDestinyVendorSaleItemBaseComponent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyComponentsVendorsDestinyVendorSaleItemBaseComponent
        /// </summary>
        [Test]
        public void DestinyComponentsVendorsDestinyVendorSaleItemBaseComponentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyComponentsVendorsDestinyVendorSaleItemBaseComponent
            //Assert.IsInstanceOf(typeof(DestinyComponentsVendorsDestinyVendorSaleItemBaseComponent), instance);
        }


        /// <summary>
        /// Test the property 'VendorItemIndex'
        /// </summary>
        [Test]
        public void VendorItemIndexTest()
        {
            // TODO unit test for the property 'VendorItemIndex'
        }
        /// <summary>
        /// Test the property 'ItemHash'
        /// </summary>
        [Test]
        public void ItemHashTest()
        {
            // TODO unit test for the property 'ItemHash'
        }
        /// <summary>
        /// Test the property 'OverrideStyleItemHash'
        /// </summary>
        [Test]
        public void OverrideStyleItemHashTest()
        {
            // TODO unit test for the property 'OverrideStyleItemHash'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Costs'
        /// </summary>
        [Test]
        public void CostsTest()
        {
            // TODO unit test for the property 'Costs'
        }
        /// <summary>
        /// Test the property 'OverrideNextRefreshDate'
        /// </summary>
        [Test]
        public void OverrideNextRefreshDateTest()
        {
            // TODO unit test for the property 'OverrideNextRefreshDate'
        }

    }

}
