/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing DestinyProgressionDestinyFactionProgression
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyProgressionDestinyFactionProgressionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyProgressionDestinyFactionProgression
        //private DestinyProgressionDestinyFactionProgression instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyProgressionDestinyFactionProgression
            //instance = new DestinyProgressionDestinyFactionProgression();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyProgressionDestinyFactionProgression
        /// </summary>
        [Test]
        public void DestinyProgressionDestinyFactionProgressionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DestinyProgressionDestinyFactionProgression
            //Assert.IsInstanceOf(typeof(DestinyProgressionDestinyFactionProgression), instance);
        }


        /// <summary>
        /// Test the property 'FactionHash'
        /// </summary>
        [Test]
        public void FactionHashTest()
        {
            // TODO unit test for the property 'FactionHash'
        }
        /// <summary>
        /// Test the property 'FactionVendorIndex'
        /// </summary>
        [Test]
        public void FactionVendorIndexTest()
        {
            // TODO unit test for the property 'FactionVendorIndex'
        }
        /// <summary>
        /// Test the property 'ProgressionHash'
        /// </summary>
        [Test]
        public void ProgressionHashTest()
        {
            // TODO unit test for the property 'ProgressionHash'
        }
        /// <summary>
        /// Test the property 'DailyProgress'
        /// </summary>
        [Test]
        public void DailyProgressTest()
        {
            // TODO unit test for the property 'DailyProgress'
        }
        /// <summary>
        /// Test the property 'DailyLimit'
        /// </summary>
        [Test]
        public void DailyLimitTest()
        {
            // TODO unit test for the property 'DailyLimit'
        }
        /// <summary>
        /// Test the property 'WeeklyProgress'
        /// </summary>
        [Test]
        public void WeeklyProgressTest()
        {
            // TODO unit test for the property 'WeeklyProgress'
        }
        /// <summary>
        /// Test the property 'WeeklyLimit'
        /// </summary>
        [Test]
        public void WeeklyLimitTest()
        {
            // TODO unit test for the property 'WeeklyLimit'
        }
        /// <summary>
        /// Test the property 'CurrentProgress'
        /// </summary>
        [Test]
        public void CurrentProgressTest()
        {
            // TODO unit test for the property 'CurrentProgress'
        }
        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Test]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
        /// <summary>
        /// Test the property 'LevelCap'
        /// </summary>
        [Test]
        public void LevelCapTest()
        {
            // TODO unit test for the property 'LevelCap'
        }
        /// <summary>
        /// Test the property 'StepIndex'
        /// </summary>
        [Test]
        public void StepIndexTest()
        {
            // TODO unit test for the property 'StepIndex'
        }
        /// <summary>
        /// Test the property 'ProgressToNextLevel'
        /// </summary>
        [Test]
        public void ProgressToNextLevelTest()
        {
            // TODO unit test for the property 'ProgressToNextLevel'
        }
        /// <summary>
        /// Test the property 'NextLevelAt'
        /// </summary>
        [Test]
        public void NextLevelAtTest()
        {
            // TODO unit test for the property 'NextLevelAt'
        }
        /// <summary>
        /// Test the property 'CurrentResetCount'
        /// </summary>
        [Test]
        public void CurrentResetCountTest()
        {
            // TODO unit test for the property 'CurrentResetCount'
        }
        /// <summary>
        /// Test the property 'SeasonResets'
        /// </summary>
        [Test]
        public void SeasonResetsTest()
        {
            // TODO unit test for the property 'SeasonResets'
        }
        /// <summary>
        /// Test the property 'RewardItemStates'
        /// </summary>
        [Test]
        public void RewardItemStatesTest()
        {
            // TODO unit test for the property 'RewardItemStates'
        }

    }

}
