/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing ForumPollResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ForumPollResponseTests
    {
        // TODO uncomment below to declare an instance variable for ForumPollResponse
        //private ForumPollResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ForumPollResponse
            //instance = new ForumPollResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForumPollResponse
        /// </summary>
        [Test]
        public void ForumPollResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ForumPollResponse
            //Assert.IsInstanceOf(typeof(ForumPollResponse), instance);
        }


        /// <summary>
        /// Test the property 'TopicId'
        /// </summary>
        [Test]
        public void TopicIdTest()
        {
            // TODO unit test for the property 'TopicId'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'TotalVotes'
        /// </summary>
        [Test]
        public void TotalVotesTest()
        {
            // TODO unit test for the property 'TotalVotes'
        }

    }

}
