/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing GroupsV2GroupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupsV2GroupResponseTests
    {
        // TODO uncomment below to declare an instance variable for GroupsV2GroupResponse
        //private GroupsV2GroupResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupsV2GroupResponse
            //instance = new GroupsV2GroupResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupsV2GroupResponse
        /// </summary>
        [Test]
        public void GroupsV2GroupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GroupsV2GroupResponse
            //Assert.IsInstanceOf(typeof(GroupsV2GroupResponse), instance);
        }


        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Test]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }
        /// <summary>
        /// Test the property 'Founder'
        /// </summary>
        [Test]
        public void FounderTest()
        {
            // TODO unit test for the property 'Founder'
        }
        /// <summary>
        /// Test the property 'AlliedIds'
        /// </summary>
        [Test]
        public void AlliedIdsTest()
        {
            // TODO unit test for the property 'AlliedIds'
        }
        /// <summary>
        /// Test the property 'ParentGroup'
        /// </summary>
        [Test]
        public void ParentGroupTest()
        {
            // TODO unit test for the property 'ParentGroup'
        }
        /// <summary>
        /// Test the property 'AllianceStatus'
        /// </summary>
        [Test]
        public void AllianceStatusTest()
        {
            // TODO unit test for the property 'AllianceStatus'
        }
        /// <summary>
        /// Test the property 'GroupJoinInviteCount'
        /// </summary>
        [Test]
        public void GroupJoinInviteCountTest()
        {
            // TODO unit test for the property 'GroupJoinInviteCount'
        }
        /// <summary>
        /// Test the property 'CurrentUserMembershipsInactiveForDestiny'
        /// </summary>
        [Test]
        public void CurrentUserMembershipsInactiveForDestinyTest()
        {
            // TODO unit test for the property 'CurrentUserMembershipsInactiveForDestiny'
        }
        /// <summary>
        /// Test the property 'CurrentUserMemberMap'
        /// </summary>
        [Test]
        public void CurrentUserMemberMapTest()
        {
            // TODO unit test for the property 'CurrentUserMemberMap'
        }
        /// <summary>
        /// Test the property 'CurrentUserPotentialMemberMap'
        /// </summary>
        [Test]
        public void CurrentUserPotentialMemberMapTest()
        {
            // TODO unit test for the property 'CurrentUserPotentialMemberMap'
        }

    }

}
