/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetApi.Api;
using BungieNetApi.Model;
using BungieNetApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetApi.Test
{
    /// <summary>
    ///  Class for testing GroupsV2GroupMembership
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupsV2GroupMembershipTests
    {
        // TODO uncomment below to declare an instance variable for GroupsV2GroupMembership
        //private GroupsV2GroupMembership instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupsV2GroupMembership
            //instance = new GroupsV2GroupMembership();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupsV2GroupMembership
        /// </summary>
        [Test]
        public void GroupsV2GroupMembershipInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GroupsV2GroupMembership
            //Assert.IsInstanceOf(typeof(GroupsV2GroupMembership), instance);
        }


        /// <summary>
        /// Test the property 'Member'
        /// </summary>
        [Test]
        public void MemberTest()
        {
            // TODO unit test for the property 'Member'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

    }

}
